import numpy as numpy

# Semantic Cube

Cube = numpy.zeros((12, 3, 3))

# CUBE
# x = operator, y = operand1, z = operand2
# Operands:
CUBE_PLUS = 0
CUBE_MINUS = 1
CUBE_TIMES = 2
CUBE_DIVIDE = 3
CUBE_GREATERTHAN = 4
CUBE_GREATEREQUAL = 5
CUBE_LESSTHAN = 6
CUBE_LESSEQUAL = 7
CUBE_EQUAL = 8
CUBE_NOTEQUAL = 9
CUBE_AND = 10
CUBE_OR = 11

# TYPES
CUBE_INT = 0
CUBE_DECIMAL = 1
CUBE_BOOL = 2
CUBE_ERROR = -1


def InitializeCube():
    # PLUS
    Cube[CUBE_PLUS, CUBE_INT, CUBE_INT] = CUBE_INT
    Cube[CUBE_PLUS, CUBE_INT, CUBE_DECIMAL] = CUBE_DECIMAL
    Cube[CUBE_PLUS, CUBE_INT, CUBE_BOOL] = CUBE_ERROR
    Cube[CUBE_PLUS, CUBE_DECIMAL, CUBE_INT] = CUBE_DECIMAL
    Cube[CUBE_PLUS, CUBE_DECIMAL, CUBE_DECIMAL] = CUBE_DECIMAL
    Cube[CUBE_PLUS, CUBE_DECIMAL, CUBE_BOOL] = CUBE_ERROR
    Cube[CUBE_PLUS, CUBE_BOOL, CUBE_INT] = CUBE_ERROR
    Cube[CUBE_PLUS, CUBE_BOOL, CUBE_DECIMAL] = CUBE_ERROR
    Cube[CUBE_PLUS, CUBE_BOOL, CUBE_BOOL] = CUBE_ERROR

    # MINUS
    Cube[CUBE_MINUS, CUBE_INT, CUBE_INT] = CUBE_INT
    Cube[CUBE_MINUS, CUBE_INT, CUBE_DECIMAL] = CUBE_DECIMAL
    Cube[CUBE_MINUS, CUBE_INT, CUBE_BOOL] = CUBE_ERROR
    Cube[CUBE_MINUS, CUBE_DECIMAL, CUBE_INT] = CUBE_DECIMAL
    Cube[CUBE_MINUS, CUBE_DECIMAL, CUBE_DECIMAL] = CUBE_DECIMAL
    Cube[CUBE_MINUS, CUBE_DECIMAL, CUBE_BOOL] = CUBE_ERROR
    Cube[CUBE_MINUS, CUBE_BOOL, CUBE_INT] = CUBE_ERROR
    Cube[CUBE_MINUS, CUBE_BOOL, CUBE_DECIMAL] = CUBE_ERROR
    Cube[CUBE_MINUS, CUBE_BOOL, CUBE_BOOL] = CUBE_ERROR
    
    # TIMES
    Cube[CUBE_TIMES, CUBE_INT, CUBE_INT] = CUBE_INT
    Cube[CUBE_TIMES, CUBE_INT, CUBE_DECIMAL] = CUBE_DECIMAL
    Cube[CUBE_TIMES, CUBE_INT, CUBE_BOOL] = CUBE_ERROR
    Cube[CUBE_TIMES, CUBE_DECIMAL, CUBE_INT] = CUBE_DECIMAL
    Cube[CUBE_TIMES, CUBE_DECIMAL, CUBE_DECIMAL] = CUBE_DECIMAL
    Cube[CUBE_TIMES, CUBE_DECIMAL, CUBE_BOOL] = CUBE_ERROR
    Cube[CUBE_TIMES, CUBE_BOOL, CUBE_INT] = CUBE_ERROR
    Cube[CUBE_TIMES, CUBE_BOOL, CUBE_DECIMAL] = CUBE_ERROR
    Cube[CUBE_TIMES, CUBE_BOOL, CUBE_BOOL] = CUBE_ERROR

    # DIVIDE
    Cube[CUBE_DIVIDE, CUBE_INT, CUBE_INT] = CUBE_DECIMAL
    Cube[CUBE_DIVIDE, CUBE_INT, CUBE_DECIMAL] = CUBE_DECIMAL
    Cube[CUBE_DIVIDE, CUBE_INT, CUBE_BOOL] = CUBE_ERROR
    Cube[CUBE_DIVIDE, CUBE_DECIMAL, CUBE_INT] = CUBE_DECIMAL
    Cube[CUBE_DIVIDE, CUBE_DECIMAL, CUBE_DECIMAL] = CUBE_DECIMAL
    Cube[CUBE_DIVIDE, CUBE_DECIMAL, CUBE_BOOL] = CUBE_ERROR
    Cube[CUBE_DIVIDE, CUBE_BOOL, CUBE_INT] = CUBE_ERROR
    Cube[CUBE_DIVIDE, CUBE_BOOL, CUBE_DECIMAL] = CUBE_ERROR
    Cube[CUBE_DIVIDE, CUBE_BOOL, CUBE_BOOL] = CUBE_ERROR

    # GREATERTHAN
    Cube[CUBE_GREATERTHAN, CUBE_INT, CUBE_INT] = CUBE_BOOL
    Cube[CUBE_GREATERTHAN, CUBE_INT, CUBE_DECIMAL] = CUBE_BOOL
    Cube[CUBE_GREATERTHAN, CUBE_INT, CUBE_BOOL] = CUBE_ERROR
    Cube[CUBE_GREATERTHAN, CUBE_DECIMAL, CUBE_INT] = CUBE_BOOL
    Cube[CUBE_GREATERTHAN, CUBE_DECIMAL, CUBE_DECIMAL] = CUBE_BOOL
    Cube[CUBE_GREATERTHAN, CUBE_DECIMAL, CUBE_BOOL] = CUBE_ERROR
    Cube[CUBE_GREATERTHAN, CUBE_BOOL, CUBE_INT] = CUBE_ERROR
    Cube[CUBE_GREATERTHAN, CUBE_BOOL, CUBE_DECIMAL] = CUBE_ERROR
    Cube[CUBE_GREATERTHAN, CUBE_BOOL, CUBE_BOOL] = CUBE_ERROR

    # GREATEREQUAL
    Cube[CUBE_GREATEREQUAL, CUBE_INT, CUBE_INT] = CUBE_BOOL
    Cube[CUBE_GREATEREQUAL, CUBE_INT, CUBE_DECIMAL] = CUBE_BOOL
    Cube[CUBE_GREATEREQUAL, CUBE_INT, CUBE_BOOL] = CUBE_ERROR
    Cube[CUBE_GREATEREQUAL, CUBE_DECIMAL, CUBE_INT] = CUBE_BOOL
    Cube[CUBE_GREATEREQUAL, CUBE_DECIMAL, CUBE_DECIMAL] = CUBE_BOOL
    Cube[CUBE_GREATEREQUAL, CUBE_DECIMAL, CUBE_BOOL] = CUBE_ERROR
    Cube[CUBE_GREATEREQUAL, CUBE_BOOL, CUBE_INT] = CUBE_ERROR
    Cube[CUBE_GREATEREQUAL, CUBE_BOOL, CUBE_DECIMAL] = CUBE_ERROR
    Cube[CUBE_GREATEREQUAL, CUBE_BOOL, CUBE_BOOL] = CUBE_ERROR

    # LESSTHAN
    Cube[CUBE_LESSTHAN, CUBE_INT, CUBE_INT] = CUBE_BOOL
    Cube[CUBE_LESSTHAN, CUBE_INT, CUBE_DECIMAL] = CUBE_BOOL
    Cube[CUBE_LESSTHAN, CUBE_INT, CUBE_BOOL] = CUBE_ERROR
    Cube[CUBE_LESSTHAN, CUBE_DECIMAL, CUBE_INT] = CUBE_BOOL
    Cube[CUBE_LESSTHAN, CUBE_DECIMAL, CUBE_DECIMAL] = CUBE_BOOL
    Cube[CUBE_LESSTHAN, CUBE_DECIMAL, CUBE_BOOL] = CUBE_ERROR
    Cube[CUBE_LESSTHAN, CUBE_BOOL, CUBE_INT] = CUBE_ERROR
    Cube[CUBE_LESSTHAN, CUBE_BOOL, CUBE_DECIMAL] = CUBE_ERROR
    Cube[CUBE_LESSTHAN, CUBE_BOOL, CUBE_BOOL] = CUBE_ERROR

    # LESSEQUAL
    Cube[CUBE_LESSEQUAL, CUBE_INT, CUBE_INT] = CUBE_BOOL
    Cube[CUBE_LESSEQUAL, CUBE_INT, CUBE_DECIMAL] = CUBE_BOOL
    Cube[CUBE_LESSEQUAL, CUBE_INT, CUBE_BOOL] = CUBE_ERROR
    Cube[CUBE_LESSEQUAL, CUBE_DECIMAL, CUBE_INT] = CUBE_BOOL
    Cube[CUBE_LESSEQUAL, CUBE_DECIMAL, CUBE_DECIMAL] = CUBE_BOOL
    Cube[CUBE_LESSEQUAL, CUBE_DECIMAL, CUBE_BOOL] = CUBE_ERROR
    Cube[CUBE_LESSEQUAL, CUBE_BOOL, CUBE_INT] = CUBE_ERROR
    Cube[CUBE_LESSEQUAL, CUBE_BOOL, CUBE_DECIMAL] = CUBE_ERROR
    Cube[CUBE_LESSEQUAL, CUBE_BOOL, CUBE_BOOL] = CUBE_ERROR

    # EQUAL
    Cube[CUBE_EQUAL, CUBE_INT, CUBE_INT] = CUBE_BOOL
    Cube[CUBE_EQUAL, CUBE_INT, CUBE_DECIMAL] = CUBE_BOOL
    Cube[CUBE_EQUAL, CUBE_INT, CUBE_BOOL] = CUBE_ERROR
    Cube[CUBE_EQUAL, CUBE_DECIMAL, CUBE_INT] = CUBE_BOOL
    Cube[CUBE_EQUAL, CUBE_DECIMAL, CUBE_DECIMAL] = CUBE_BOOL
    Cube[CUBE_EQUAL, CUBE_DECIMAL, CUBE_BOOL] = CUBE_ERROR
    Cube[CUBE_EQUAL, CUBE_BOOL, CUBE_INT] = CUBE_ERROR
    Cube[CUBE_EQUAL, CUBE_BOOL, CUBE_DECIMAL] = CUBE_ERROR
    Cube[CUBE_EQUAL, CUBE_BOOL, CUBE_BOOL] = CUBE_BOOL

    # NOTEQUAL
    Cube[CUBE_NOTEQUAL, CUBE_INT, CUBE_INT] = CUBE_BOOL
    Cube[CUBE_NOTEQUAL, CUBE_INT, CUBE_DECIMAL] = CUBE_BOOL
    Cube[CUBE_NOTEQUAL, CUBE_INT, CUBE_BOOL] = CUBE_ERROR
    Cube[CUBE_NOTEQUAL, CUBE_DECIMAL, CUBE_INT] = CUBE_BOOL
    Cube[CUBE_NOTEQUAL, CUBE_DECIMAL, CUBE_DECIMAL] = CUBE_BOOL
    Cube[CUBE_NOTEQUAL, CUBE_DECIMAL, CUBE_BOOL] = CUBE_ERROR
    Cube[CUBE_NOTEQUAL, CUBE_BOOL, CUBE_INT] = CUBE_ERROR
    Cube[CUBE_NOTEQUAL, CUBE_BOOL, CUBE_DECIMAL] = CUBE_ERROR
    Cube[CUBE_NOTEQUAL, CUBE_BOOL, CUBE_BOOL] = CUBE_BOOL

    # AND
    Cube[CUBE_AND, CUBE_INT, CUBE_INT] = CUBE_ERROR
    Cube[CUBE_AND, CUBE_INT, CUBE_DECIMAL] = CUBE_ERROR
    Cube[CUBE_AND, CUBE_INT, CUBE_BOOL] = CUBE_ERROR
    Cube[CUBE_AND, CUBE_DECIMAL, CUBE_INT] = CUBE_ERROR
    Cube[CUBE_AND, CUBE_DECIMAL, CUBE_DECIMAL] = CUBE_ERROR
    Cube[CUBE_AND, CUBE_DECIMAL, CUBE_BOOL] = CUBE_ERROR
    Cube[CUBE_AND, CUBE_BOOL, CUBE_INT] = CUBE_ERROR
    Cube[CUBE_AND, CUBE_BOOL, CUBE_DECIMAL] = CUBE_ERROR
    Cube[CUBE_AND, CUBE_BOOL, CUBE_BOOL] = CUBE_BOOL

    # OR
    Cube[CUBE_OR, CUBE_INT, CUBE_INT] = CUBE_ERROR
    Cube[CUBE_OR, CUBE_INT, CUBE_DECIMAL] = CUBE_ERROR
    Cube[CUBE_OR, CUBE_INT, CUBE_BOOL] = CUBE_ERROR
    Cube[CUBE_OR, CUBE_DECIMAL, CUBE_INT] = CUBE_ERROR
    Cube[CUBE_OR, CUBE_DECIMAL, CUBE_DECIMAL] = CUBE_ERROR
    Cube[CUBE_OR, CUBE_DECIMAL, CUBE_BOOL] = CUBE_ERROR
    Cube[CUBE_OR, CUBE_BOOL, CUBE_INT] = CUBE_ERROR
    Cube[CUBE_OR, CUBE_BOOL, CUBE_DECIMAL] = CUBE_ERROR
    Cube[CUBE_OR, CUBE_BOOL, CUBE_BOOL] = CUBE_BOOL